AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
    - spec/**/*

Style/Documentation:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 12

Layout/HashAlignment:
  EnforcedColonStyle: table

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
